### PR TITLE
Enhance the logic to wait for k8s resources in `create_cluster.sh`

### LINKED ISSUE #553: Enhance create_cluster.sh to handle slow infrastructure at stage `Waiting for Cluster=Ready` better
I'm facing some probably slow API responses after the latest changes for R5, maybe related to #552?
```
terraform_data.mgmtcluster_bootstrap_files (remote-exec): # Waiting for Cluster=Ready
terraform_data.mgmtcluster_bootstrap_files (remote-exec): error: no matching resources found
```
Running `create_cluster.sh testcluster` again results in:
```
# rendering clusterconfig from template
 Overwriting config for testcluster
 Warning: Cluster exists
 Hit ^C to interrupt
# Security groups for cilium
# apply configuration and deploy cluster testcluster
[...]
# Waiting for Cluster=Ready
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/testcluster-control-plane condition met
machine.cluster.x-k8s.io/testcluster-control-plane-vhshr condition met
[...]
```

Has anyone else have seen this yet?

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
This PR add additional logic to wait for k8s resources `` and `` to be created before `kubectl wait` is called. This adds two new bash functions for repetitive code.

Closes #553

### CODE REVIEW

File: terraform/files/bin/create_cluster.sh [hunk 1]
```diff
@@ -4,6 +4,25 @@
...
+    echo "[$SLEEP] waiting for $1"
+    sleep 10
+    let SLEEP+=10
+  done
+}
+
+wait_for_k8s_resources_matching() {
+  local SLEEP=0
+  until [ ! -z $(kubectl $3 get $2 --template '{{if len .items}}{{with index .items 0}}{{.metadata.name}}{{end}}{{end}}') ]; do
+    echo "[$SLEEP] waiting for $1"
```
Comment (fdobrovolny) [inline terraform/files/bin/create_cluster.sh:20]: Just a UX suggestion, first I thought you wanted to implement some nice back off algorithm. Then I realized how you meant it. I would add some notion to show it is seconds.

**Review by fdobrovolny — APPROVED** [review]
LGTM however it could be worth if someone actually tested it. I can try it tommorow.

File: terraform/files/bin/create_cluster.sh [hunk 2]
```diff
@@ -149,15 +168,12 @@ fi
 echo "# apply configuration and deploy cluster ${CLUSTER_NAME}"
 kubectl apply -f ~/${CLUSTER_NAME}/${CLUSTER_NAME}-config.yaml || exit 3
 
-#Waiting for Clusterstate Ready
+# Waiting for Cluster=Ready
+wait_for_k8s_resource_matching kubeadmcontrolplanes/${CLUSTER_NAME}-control-plane
+wait_for_k8s_resources_matching machines/${CLUSTER_NAME} "machines -l cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}"
+
 echo "# Waiting for Cluster=Ready"
```
Comment (chess-knight) [inline terraform/files/bin/create_cluster.sh:175]: Suggestion: Move this *cluster* **echo**(line 175) three lines above as well as *kube-proxy* **echo**(line 199).

**Review by chess-knight — APPROVED** [review]
According to my tests, it works.
Just one minor suggestion.

File: terraform/files/bin/create_cluster.sh (hunk 2 above)
Comment (NotTheEvilOne) [reply terraform/files/bin/create_cluster.sh:175]: I put the wait_* calls above the echos because while waiting for e.g. `kubeadmcontrolplanes/${CLUSTER_NAME}-control-plane` it is printing `[0] waiting for kubeadmcontrolplanes/${CLUSTER_NAME}-control-plane` while the below `kubectl wait` executions prints nothing and have a timeout of e.g. 5 minutes where you are left in the dark what is happening. For debugging purposes you know this way that it already waited successfully for the resources to appear (wait_* calls) but is now at the `kubectl wait` stage.

That being said let me know if you still prefer it the other way around. I can move the lines up easily :smile:

Comment (chess-knight) [reply terraform/files/bin/create_cluster.sh:175]: Thank you, it makes sense to me. We can keep it as is.

**Review by DEiselt — APPROVED** [review]

**Comment by berendt** [comment]
I would still suggest applying ansible-lint and yamllint to the plays. Then we have things here in a uniform way like in OSISM. ansible-lint and yaml-lint jobs are already available ready to use in osism/zuul-jobs. You can also make the osism/zuul-jobs usable in SCS Zuul. Then you don't need to copy them.
